import type { TarotCard } from "@/lib/tarot/types";

export const TAROT_DECK_SEED: TarotCard[] = [
  {
    id: "5a1a3d95-f65f-4f18-b31d-6040a96f0f11",
    slug: "the-star",
    nameTr: "Yıldız",
    arcana: "major",
    suit: "major",
    rank: "17",
    uprightKeywords: ["umut", "yenilenme", "ilham"],
    reversedKeywords: ["dağınık inanç", "enerji düşüşü", "gecikmiş iyimserlik"],
    energy: "arı ve sakin",
  },
  {
    id: "4ec6f0b8-a56b-4797-a3dd-69bc1dbf6761",
    slug: "the-empress",
    nameTr: "İmparatoriçe",
    arcana: "major",
    suit: "major",
    rank: "3",
    uprightKeywords: ["bereket", "çekim", "duygusal beslenme"],
    reversedKeywords: ["aşırı verme", "sınır kaybı", "duygusal yorgunluk"],
    energy: "yumuşak ve üretken",
  },
  {
    id: "ae7fb86d-f7b0-4f31-8580-6d4bfd690c77",
    slug: "the-chariot",
    nameTr: "Savaş Arabası",
    arcana: "major",
    suit: "major",
    rank: "7",
    uprightKeywords: ["irade", "yön", "kararlı hareket"],
    reversedKeywords: ["kontrol kaybı", "acelecilik", "dağınık hedef"],
    energy: "atak ve odaklı",
  },
  {
    id: "d9685fe9-dad6-4278-a0d5-cf6887a8b2f5",
    slug: "queen-of-cups",
    nameTr: "Kupa Kraliçesi",
    arcana: "minor",
    suit: "cups",
    rank: "queen",
    uprightKeywords: ["sezgi", "duygusal derinlik", "şefkatli netlik"],
    reversedKeywords: ["aşırı hassasiyet", "içe kapanma", "bulanık sınırlar"],
    energy: "su gibi akışkan",
  },
  {
    id: "7fb21f7c-4457-4a9c-804f-4d0c96464611",
    slug: "two-of-swords",
    nameTr: "Kılıç İkilisi",
    arcana: "minor",
    suit: "swords",
    rank: "2",
    uprightKeywords: ["karar eşiği", "denge", "zihinsel duraksama"],
    reversedKeywords: ["kaçınma", "aşırı düşünme", "karar yorgunluğu"],
    energy: "durgun ama keskin",
  },
  {
    id: "e953d2fa-c396-4a5f-a56e-7adfaf76726a",
    slug: "ace-of-pentacles",
    nameTr: "Tılsım Ası",
    arcana: "minor",
    suit: "pentacles",
    rank: "ace",
    uprightKeywords: ["somut fırsat", "istikrar", "yeni başlangıç"],
    reversedKeywords: ["fırsatı erteleme", "zemin eksikliği", "kısa vadeli bakış"],
    energy: "topraklayıcı",
  },
  {
    id: "85ba6e11-53af-4ec2-b393-d8d2ced4f1d7",
    slug: "eight-of-wands",
    nameTr: "Değnek Sekizlisi",
    arcana: "minor",
    suit: "wands",
    rank: "8",
    uprightKeywords: ["hız", "mesaj akışı", "ivme"],
    reversedKeywords: ["tempo dağılması", "yanlış zamanlama", "iletişim gürültüsü"],
    energy: "dinamik",
  },
];
